package com.gproust.sprout

import android.util.Base64
import com.gproust.sprout.data.sync.SyncCrypto
import com.gproust.sprout.data.sync.SyncCryptoException
import com.gproust.sprout.data.sync.SyncInvitation
import com.gproust.sprout.data.sync.SyncInvitationCodec
import com.gproust.sprout.data.sync.SyncInvitationException
import com.gproust.sprout.data.sync.SyncLimits
import com.gproust.sprout.data.sync.SyncSecret
import com.gproust.sprout.data.sync.nearby.HouseholdBeacon
import com.gproust.sprout.data.sync.nearby.SyncSession
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.ByteArrayInputStream
import java.io.File

/**
 * Checks this app against the shared specification in `spec/`.
 *
 * The vectors are generated by [spec/vectors/generate.mjs] — Node, sharing no
 * code with either app — so what this proves is that Android agrees with the
 * *format*, not that iOS agrees with Android. `SproutKitTests` on the other side
 * reads the same files and asserts the same things.
 *
 * If a change here fails, the question is which of the three is wrong. Editing
 * the vectors to match new behaviour is only correct once the format itself has
 * been decided to change — see `spec/README.md`.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class SpecConformanceTest {

    private val vectors = File("../../spec/vectors")

    private fun vector(name: String) = JSONObject(File(vectors, name).readText())

    private fun String.fromHex(): ByteArray =
        chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private fun secret(): SyncSecret =
        SyncSecret(vector("secret.json").getString("secretHex").fromHex())

    /** A missing `spec/` would otherwise make every test below vacuously pass. */
    @Test
    fun `the vectors are present`() {
        assertTrue(
            "spec/vectors not found at ${vectors.absolutePath} — run `node spec/vectors/generate.mjs`",
            vectors.isDirectory && File(vectors, "secret.json").isFile,
        )
    }

    @Test
    fun `verification code matches the spec`() {
        val v = vector("secret.json")
        assertEquals(SyncSecret.SIZE_BYTES, v.getInt("sizeBytes"))
        assertEquals(v.getString("verificationCode"), secret().verificationCode())
    }

    @Test
    fun `opens a replica this app did not write`() {
        val v = vector("sealed.json")
        val sealed = Base64.decode(v.getString("sealedBase64"), Base64.NO_WRAP)

        val opened = SyncCrypto.open(sealed, secret())

        assertEquals(v.getString("plaintextUtf8"), String(opened, Charsets.UTF_8))
    }

    @Test
    fun `refuses a replica whose bytes were altered`() {
        val v = vector("sealed.json")
        val tampered = Base64.decode(v.getString("tamperedBase64"), Base64.NO_WRAP)

        assertThrows(SyncCryptoException::class.java) { SyncCrypto.open(tampered, secret()) }
    }

    /** The header is associated data, so rewriting the version must not work. */
    @Test
    fun `refuses a replica whose version byte was rewritten`() {
        val v = vector("sealed.json")
        val rewritten = Base64.decode(v.getString("rewrittenVersionBase64"), Base64.NO_WRAP)

        assertThrows(SyncCryptoException::class.java) { SyncCrypto.open(rewritten, secret()) }
    }

    @Test
    fun `beacon values and advertised uuids match the spec`() {
        val v = vector("beacon.json")
        assertEquals(HouseholdBeacon.WINDOW_MS, v.getLong("windowMs"))
        assertEquals(HouseholdBeacon.VALUE_BYTES, v.getInt("valueBytes"))

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val at = case.getLong("at")
            assertEquals(
                "beacon for at=$at",
                case.getString("beaconHex"),
                HouseholdBeacon.value(secret(), at).toHex(),
            )
        }
    }

    /**
     * The UUID form is what ADR-0016 moves the advertisement to, and Android
     * does not implement it yet. Pinning the derivation here means the day it
     * does, it either matches iOS or fails this test — rather than shipping a
     * transport that silently cannot see an iPhone.
     */
    @Test
    fun `the advertised uuid derivation matches the spec`() {
        val v = vector("beacon.json")
        val label = v.getString("advertUuidLabel")
        val mac = javax.crypto.Mac.getInstance("HmacSHA256").apply {
            init(javax.crypto.spec.SecretKeySpec(secret().bytes, "HmacSHA256"))
        }

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val window = case.getLong("window")
            val bytes = mac.doFinal("$label$window".toByteArray(Charsets.US_ASCII)).copyOf(16)
            val hex = bytes.toHex()
            val uuid = "${hex.substring(0, 8)}-${hex.substring(8, 12)}-${hex.substring(12, 16)}-" +
                "${hex.substring(16, 20)}-${hex.substring(20, 32)}"

            assertEquals("advertised uuid for window=$window", case.getString("advertUuid"), uuid)
        }
    }

    @Test
    fun `session framing matches the spec`() {
        val v = vector("session-frame.json")
        assertEquals(SyncSession.MAX_PAYLOAD_BYTES, v.getInt("maxPayloadBytes"))
        val frame = Base64.decode(v.getString("frameBase64"), Base64.NO_WRAP)

        // Reading the vector's frame is the direction that matters: it is bytes
        // this app did not produce.
        val read = SyncSession.exchange(
            input = ByteArrayInputStream(frame),
            output = java.io.ByteArrayOutputStream(),
            mine = ByteArray(0),
        )

        assertArrayEquals(v.getString("payloadUtf8").toByteArray(Charsets.UTF_8), read)
    }

    @Test
    fun `invitation fields and expiry match the spec`() {
        val v = vector("invitation.json")
        assertEquals(SyncInvitation.VALID_FOR_MS, v.getLong("validForMs"))
        val fields = v.getJSONObject("fields")
        val createdAt = fields.getLong("createdAt")

        val decoded = SyncInvitationCodec.decode(
            fields.toString().toByteArray(Charsets.UTF_8),
            now = createdAt + 1_000,
        )

        assertEquals(fields.getString("householdId"), decoded.householdId)
        assertEquals(fields.getString("fromName"), decoded.fromName)
        assertEquals(createdAt, decoded.createdAt)
        assertArrayEquals(
            Base64.decode(fields.getString("secret"), Base64.NO_WRAP),
            decoded.secret.bytes,
        )

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val name = case.getString("name")
            val now = case.getLong("now")
            val document = JSONObject(fields.toString()).apply {
                if (case.has("formatVersion")) put("formatVersion", case.getInt("formatVersion"))
            }
            val bytes = document.toString().toByteArray(Charsets.UTF_8)

            when (val expect = case.getString("expect")) {
                "accepted" -> SyncInvitationCodec.decode(bytes, now)
                "expired" -> assertThrows(name, SyncInvitationException.Expired::class.java) {
                    SyncInvitationCodec.decode(bytes, now)
                }
                "tooNew" -> assertThrows(name, SyncInvitationException.TooNew::class.java) {
                    SyncInvitationCodec.decode(bytes, now)
                }
                else -> throw AssertionError("unknown expectation $expect in case $name")
            }
        }
    }

    @Test
    fun `nesting limits match the spec`() {
        val v = vector("json-depth.json")
        assertEquals(SyncLimits.MAX_JSON_DEPTH, v.getInt("maxJsonDepth"))

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            assertEquals(
                case.getString("name"),
                case.getBoolean("exceeds"),
                SyncLimits.exceedsMaxJsonDepth(case.getString("text")),
            )
        }
    }
}
