package com.gproust.sprout

import android.util.Base64
import com.gproust.sprout.data.sync.SyncCrypto
import com.gproust.sprout.data.sync.SyncCryptoException
import com.gproust.sprout.data.sync.SyncInvitation
import com.gproust.sprout.data.sync.SyncInvitationCodec
import com.gproust.sprout.data.sync.SyncInvitationException
import com.gproust.sprout.data.sync.SyncLimits
import com.gproust.sprout.data.local.BreastSide
import com.gproust.sprout.data.sync.SyncPayloadCodec
import com.gproust.sprout.data.sync.SyncPayloadException
import com.gproust.sprout.data.sync.SyncSecret
import com.gproust.sprout.data.sync.nearby.HouseholdBeacon
import com.gproust.sprout.data.sync.nearby.L2capPsm
import com.gproust.sprout.data.sync.nearby.SyncSession
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.ByteArrayInputStream
import java.io.File

/**
 * Checks this app against the shared specification in `spec/`.
 *
 * The vectors are generated by [spec/vectors/generate.mjs] — Node, sharing no
 * code with either app — so what this proves is that Android agrees with the
 * *format*, not that iOS agrees with Android. `SproutKitTests` on the other side
 * reads the same files and asserts the same things.
 *
 * If a change here fails, the question is which of the three is wrong. Editing
 * the vectors to match new behaviour is only correct once the format itself has
 * been decided to change — see `spec/README.md`.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class SpecConformanceTest {

    private val vectors = File("../../spec/vectors")

    private fun vector(name: String) = JSONObject(File(vectors, name).readText())

    private fun String.fromHex(): ByteArray =
        chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private fun secret(): SyncSecret =
        SyncSecret(vector("secret.json").getString("secretHex").fromHex())

    /** A missing `spec/` would otherwise make every test below vacuously pass. */
    @Test
    fun `the vectors are present`() {
        assertTrue(
            "spec/vectors not found at ${vectors.absolutePath} — run `node spec/vectors/generate.mjs`",
            vectors.isDirectory && File(vectors, "secret.json").isFile,
        )
    }

    @Test
    fun `verification code matches the spec`() {
        val v = vector("secret.json")
        assertEquals(SyncSecret.SIZE_BYTES, v.getInt("sizeBytes"))
        assertEquals(v.getString("verificationCode"), secret().verificationCode())
    }

    @Test
    fun `opens a replica this app did not write`() {
        val v = vector("sealed.json")
        val sealed = Base64.decode(v.getString("sealedBase64"), Base64.NO_WRAP)

        val opened = SyncCrypto.open(sealed, secret())

        assertEquals(v.getString("plaintextUtf8"), String(opened, Charsets.UTF_8))
    }

    @Test
    fun `refuses a replica whose bytes were altered`() {
        val v = vector("sealed.json")
        val tampered = Base64.decode(v.getString("tamperedBase64"), Base64.NO_WRAP)

        assertThrows(SyncCryptoException::class.java) { SyncCrypto.open(tampered, secret()) }
    }

    /** The header is associated data, so rewriting the version must not work. */
    @Test
    fun `refuses a replica whose version byte was rewritten`() {
        val v = vector("sealed.json")
        val rewritten = Base64.decode(v.getString("rewrittenVersionBase64"), Base64.NO_WRAP)

        assertThrows(SyncCryptoException::class.java) { SyncCrypto.open(rewritten, secret()) }
    }

    @Test
    fun `beacon values and advertised uuids match the spec`() {
        val v = vector("beacon.json")
        assertEquals(HouseholdBeacon.WINDOW_MS, v.getLong("windowMs"))
        assertEquals(HouseholdBeacon.VALUE_BYTES, v.getInt("valueBytes"))

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val at = case.getLong("at")
            assertEquals(
                "beacon for at=$at",
                case.getString("beaconHex"),
                HouseholdBeacon.value(secret(), at).toHex(),
            )
        }
    }

    /**
     * The UUID form is what ADR-0016 moves the advertisement to, and the only
     * one an iPhone can send or see. A derivation that drifted by a byte would
     * not fail anywhere else: the two apps would simply never find each other,
     * and report an empty room.
     */
    @Test
    fun `the advertised uuid derivation matches the spec`() {
        val v = vector("beacon.json")
        assertEquals(HouseholdBeacon.ADVERT_LABEL, v.getString("advertUuidLabel"))

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val at = case.getLong("at")
            assertEquals(
                "advertised uuid for at=$at",
                case.getString("advertUuid"),
                HouseholdBeacon.advertUuid(secret(), at).toString(),
            )
            assertEquals("window for at=$at", case.getLong("window"), HouseholdBeacon.window(at))
        }
    }

    /**
     * Where the L2CAP channel is announced (ADR-0016). Two apps that derived the
     * same advertisement but read a different characteristic would connect and
     * then find nothing — a failure with no error in it anywhere.
     */
    @Test
    fun `the psm characteristic and its encoding match the spec`() {
        val v = vector("l2cap.json")
        assertEquals(v.getString("characteristicUuid"), L2capPsm.CHARACTERISTIC_UUID.toString())
        assertEquals(v.getInt("psmBytes"), L2capPsm.BYTES)

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val psm = case.getInt("psm")
            assertEquals("psm $psm encoded", case.getString("hex"), L2capPsm.encode(psm).toHex())
            // And read back the way iOS would read ours.
            assertEquals("psm $psm decoded", psm, L2capPsm.decode(case.getString("hex").fromHex()))
        }
    }

    @Test
    fun `session framing matches the spec`() {
        val v = vector("session-frame.json")
        assertEquals(SyncSession.MAX_PAYLOAD_BYTES, v.getInt("maxPayloadBytes"))
        val frame = Base64.decode(v.getString("frameBase64"), Base64.NO_WRAP)

        // Reading the vector's frame is the direction that matters: it is bytes
        // this app did not produce.
        val read = SyncSession.exchange(
            input = ByteArrayInputStream(frame),
            output = java.io.ByteArrayOutputStream(),
            mine = ByteArray(0),
        )

        assertArrayEquals(v.getString("payloadUtf8").toByteArray(Charsets.UTF_8), read)
    }

    @Test
    fun `invitation fields and expiry match the spec`() {
        val v = vector("invitation.json")
        assertEquals(SyncInvitation.VALID_FOR_MS, v.getLong("validForMs"))
        val fields = v.getJSONObject("fields")
        val createdAt = fields.getLong("createdAt")

        val decoded = SyncInvitationCodec.decode(
            fields.toString().toByteArray(Charsets.UTF_8),
            now = createdAt + 1_000,
        )

        assertEquals(fields.getString("householdId"), decoded.householdId)
        assertEquals(fields.getString("fromName"), decoded.fromName)
        assertEquals(createdAt, decoded.createdAt)
        assertArrayEquals(
            Base64.decode(fields.getString("secret"), Base64.NO_WRAP),
            decoded.secret.bytes,
        )

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val name = case.getString("name")
            val now = case.getLong("now")
            val document = JSONObject(fields.toString()).apply {
                if (case.has("formatVersion")) put("formatVersion", case.getInt("formatVersion"))
            }
            val bytes = document.toString().toByteArray(Charsets.UTF_8)

            when (val expect = case.getString("expect")) {
                "accepted" -> SyncInvitationCodec.decode(bytes, now)
                "expired" -> assertThrows(name, SyncInvitationException.Expired::class.java) {
                    SyncInvitationCodec.decode(bytes, now)
                }
                "tooNew" -> assertThrows(name, SyncInvitationException.TooNew::class.java) {
                    SyncInvitationCodec.decode(bytes, now)
                }
                else -> throw AssertionError("unknown expectation $expect in case $name")
            }
        }
    }

    /**
     * The replica document, against a vector Node wrote.
     *
     * The sealing envelope has been pinned since the spec existed; the plaintext
     * inside it had not been, which left the one place a hand-written port can
     * differ by a single key and nothing say so — two phones in a household
     * simply stop syncing, and nothing errors when that happens. This closes it
     * from the Android side; `SyncPayloadTests` closes it from the other.
     */
    @Test
    fun `the replica document matches the spec`() {
        val v = vector("replica.json")
        val payload = SyncPayloadCodec.decode(
            v.getString("documentJson").toByteArray(Charsets.UTF_8),
            currentSchemaVersion = v.getInt("schemaVersion"),
        )

        assertEquals("household-vector", payload.householdId)
        assertEquals("device-vector", payload.deviceId)
        assertEquals("Vector's phone", payload.deviceName)
        assertEquals(v.getInt("rowCount"), payload.rowCount)

        // The two fields Room packs into strings have to unpack to the same
        // values on both sides: a platform that read them as anything else would
        // write a document the other could not use.
        val segments = payload.feedings.first().row.segments
        assertEquals(2, segments.size)
        assertEquals(BreastSide.LEFT, segments.first().side)
        assertEquals(1_757_400_000_000L, segments.first().startTime)
        assertEquals(listOf(540, 1260), payload.treatments.first().row.timesOfDay)

        // As-needed medicine (BDR-15). The dose names its medicine by that
        // medicine's uid — the one field in the document that points at another
        // row rather than at a baby, and the one a hand-written port could
        // quietly read as a local id.
        val paracetamol = payload.medicines.first { it.row.name == "Paracetamol" }.row
        assertEquals(360, paracetamol.minIntervalMinutes)
        assertEquals(480, paracetamol.comfortIntervalMinutes)
        assertEquals(4, paracetamol.maxPerDay)
        assertTrue(paracetamol.remindWhenDue)

        // A medicine with only a minimum gap: the other two are absent keys, not
        // zeroes, and a zero here would be a daily maximum of none allowed.
        val ibuprofen = payload.medicines.first { it.row.name == "Ibuprofen" }.row
        assertNull(ibuprofen.comfortIntervalMinutes)
        assertNull(ibuprofen.maxPerDay)

        val dose = payload.medicineDoses.single().row
        assertEquals(paracetamol.uid, dose.medicineUid)
        assertEquals(1_757_402_800_000L, dose.time)

        // A measure nobody took is an absent key, not a zero.
        assertNull(payload.growth.first().row.heightMm)
        assertNull(payload.babies.first().feedingReminderEnabled)

        // And a row that *was* deleted carries the flag, which is how a deletion
        // reaches the other phone instead of being undone by it.
        assertEquals(
            1_757_406_000_000L,
            payload.diapers.first { it.row.deletedAt != null }.row.deletedAt,
        )
    }

    /** Each refusal is its own case: "newer" and "damaged" are different sentences. */
    @Test
    fun `the replica refusals match the spec`() {
        val refusals = vector("replica.json").getJSONArray("refuses")
        for (i in 0 until refusals.length()) {
            val case = refusals.getJSONObject(i)
            val name = case.getString("name")
            val thrown = try {
                SyncPayloadCodec.decode(
                    case.getString("json").toByteArray(Charsets.UTF_8),
                    // From the vector, not a literal: a schema bump would
                    // otherwise turn every one of these into a `tooNew` that
                    // passes for the wrong reason.
                    currentSchemaVersion = vector("replica.json").getInt("schemaVersion"),
                )
                null
            } catch (e: SyncPayloadException) {
                e
            }

            assertTrue("$name: should not have decoded", thrown != null)
            when (case.getString("reason")) {
                "tooNew" -> assertTrue(name, thrown is SyncPayloadException.TooNew)
                "unreadable" -> assertTrue(name, thrown is SyncPayloadException.Unreadable)
                else -> error("unknown reason in the vector")
            }
        }
    }

    @Test
    fun `nesting limits match the spec`() {
        val v = vector("json-depth.json")
        assertEquals(SyncLimits.MAX_JSON_DEPTH, v.getInt("maxJsonDepth"))

        val cases = v.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            assertEquals(
                case.getString("name"),
                case.getBoolean("exceeds"),
                SyncLimits.exceedsMaxJsonDepth(case.getString("text")),
            )
        }
    }
}
