import Foundation
import XCTest
@testable import SproutData

/// The replica document, against `spec/vectors/replica.json`.
///
/// **This vector is the point of the exercise.** The sealing envelope was already
/// pinned by the spec; the plaintext inside it was not, which meant a hand-port of
/// the document could differ from Android's by one key and nothing would say so —
/// two phones in a household would simply stop syncing, and nothing errors when
/// that happens. The vector is generated by Node, so agreeing with it is agreeing
/// with the *format* rather than with whichever app was written first.
final class SyncPayloadTests: XCTestCase {

    private func vector() throws -> [String: Any] {
        try Vectors.load("replica.json")
    }

    private func document() throws -> Data {
        guard let json = try vector()["documentJson"] as? String else {
            throw XCTSkip("replica.json has no documentJson")
        }
        return Data(json.utf8)
    }

    // MARK: - Reading what Node wrote

    func testTheVectorDecodesRowForRow() throws {
        let payload = try SyncPayloadCodec.decode(try document(), currentSchemaVersion: 16)

        XCTAssertEqual(payload.householdId, "household-vector")
        XCTAssertEqual(payload.deviceId, "device-vector")
        XCTAssertEqual(payload.deviceName, "Vector's phone")
        XCTAssertEqual(payload.schemaVersion, 16)
        XCTAssertEqual(payload.createdAt, 1_757_400_000_000)

        let expectedRows = try vector()["rowCount"] as? Int
        XCTAssertEqual(payload.rowCount, expectedRows)
    }

    func testEveryRowTypeSurvivesTheTrip() throws {
        let payload = try SyncPayloadCodec.decode(try document(), currentSchemaVersion: 16)

        let baby = try XCTUnwrap(payload.babies.first)
        XCTAssertEqual(baby.name, "Robin")
        XCTAssertEqual(baby.birthDate, 1_755_000_000_000)
        XCTAssertFalse(baby.archived)

        let feeding = try XCTUnwrap(payload.feedings.first)
        XCTAssertEqual(feeding.babyUid, baby.uid)
        XCTAssertEqual(feeding.row.type, .BREAST)
        XCTAssertEqual(feeding.row.side, .BOTH)
        XCTAssertEqual(feeding.row.leftDurationMs, 540_000)

        let sleep = try XCTUnwrap(payload.sleeps.first)
        XCTAssertEqual(sleep.row.position, .BACK)
        XCTAssertEqual(sleep.row.place, .OTHER)
        XCTAssertEqual(sleep.row.placeNote, "pram")

        let growth = try XCTUnwrap(payload.growth.first)
        XCTAssertEqual(growth.row.weightGrams, 4200)

        let treatment = try XCTUnwrap(payload.treatments.first)
        XCTAssertEqual(treatment.row.name, "Vitamin D")
        XCTAssertEqual(treatment.row.dose, "400 IU")

        let pumping = try XCTUnwrap(payload.pumpings.first)
        XCTAssertEqual(pumping.storage, .FRIDGE)
        XCTAssertEqual(pumping.amountMl, 120)

        let tombstone = try XCTUnwrap(payload.tombstones.first)
        XCTAssertEqual(tombstone.entity, "feeding")
        XCTAssertEqual(tombstone.deletedAt, 1_757_405_000_000)
    }

    /// The two fields Room packs into strings. They have to survive as *strings*:
    /// a platform that helpfully turned them into arrays would write a document
    /// the other could not read.
    func testThePackedFieldsStayPacked() throws {
        let payload = try SyncPayloadCodec.decode(try document(), currentSchemaVersion: 16)

        let feeding = try XCTUnwrap(payload.feedings.first).row
        XCTAssertEqual(
            feeding.segments,
            "LEFT,1757400000000,1757400360000;RIGHT,1757400360000,1757400600000"
        )
        XCTAssertEqual(feeding.nursingSegments.count, 2)
        XCTAssertEqual(feeding.nursingSegments.first?.side, .LEFT)

        let treatment = try XCTUnwrap(payload.treatments.first).row
        XCTAssertEqual(treatment.timesOfDay, "540,1260")
        XCTAssertEqual(treatment.reminderTimes, [540, 1260])
    }

    /// A measure nobody took is an absent key, not a zero, and a row nobody
    /// deleted has no `deletedAt` at all.
    func testAbsentIsNullAndNullIsAbsent() throws {
        let payload = try SyncPayloadCodec.decode(try document(), currentSchemaVersion: 16)

        let baby = try XCTUnwrap(payload.babies.first)
        XCTAssertNil(baby.feedingReminderEnabled)
        XCTAssertNil(baby.feedingReminderIntervalMinutes)
        XCTAssertNil(baby.deletedAt)

        let growth = try XCTUnwrap(payload.growth.first).row
        XCTAssertNil(growth.heightMm, "nobody measured it — that is not zero")
        XCTAssertNil(growth.headMm)

        // And a row that *was* deleted carries the flag, which is how a deletion
        // reaches the other phone instead of being undone by it.
        let deleted = payload.diapers.first { $0.row.deletedAt != nil }
        XCTAssertEqual(try XCTUnwrap(deleted).row.deletedAt, 1_757_406_000_000)
    }

    /// Explicit nulls are what a different JSON writer would produce. Android
    /// never writes them, but a reader that refused them would refuse a document
    /// that is otherwise perfectly correct.
    func testAnExplicitNullReadsAsAnAbsentKey() throws {
        let json = """
        {"formatVersion":1,"schemaVersion":16,"householdId":"h","deviceId":"d",
         "createdAt":1,"babies":[{"uid":"u","updatedAt":2,"deletedAt":null,
         "name":"Robin","birthDate":3,"archived":false,
         "feedingReminderEnabled":null}]}
        """

        let payload = try SyncPayloadCodec.decode(Data(json.utf8), currentSchemaVersion: 16)
        let baby = try XCTUnwrap(payload.babies.first)

        XCTAssertNil(baby.deletedAt)
        XCTAssertNil(baby.feedingReminderEnabled)
    }

    // MARK: - What it refuses, and how it says so

    /// Each refusal is its own case, because "your partner's phone is newer than
    /// yours" and "this file is damaged" are different things to be told.
    func testItRefusesTheVectorsRefusals() throws {
        guard let refusals = try vector()["refuses"] as? [[String: Any]] else {
            throw XCTSkip("replica.json has no refusals")
        }

        for refusal in refusals {
            let name = refusal["name"] as? String ?? "?"
            let json = try XCTUnwrap(refusal["json"] as? String, name)
            let reason = try XCTUnwrap(refusal["reason"] as? String, name)

            do {
                _ = try SyncPayloadCodec.decode(Data(json.utf8), currentSchemaVersion: 16)
                XCTFail("\(name): should not have decoded")
            } catch let error as SyncPayloadError {
                switch (error, reason) {
                case (.tooNew, "tooNew"), (.unreadable, "unreadable"):
                    break
                default:
                    XCTFail("\(name): expected \(reason), got \(error)")
                }
            }
        }
    }

    /// Nesting deep enough to exhaust the stack is checked **before** parsing:
    /// on both platforms that failure is not something a `catch` can hold.
    func testImplausibleNestingIsRefusedBeforeParsing() {
        let deep = String(repeating: "[", count: 200) + String(repeating: "]", count: 200)

        XCTAssertThrowsError(
            try SyncPayloadCodec.decode(Data(deep.utf8), currentSchemaVersion: 16)
        ) { error in
            guard case .unreadable = error as? SyncPayloadError else {
                return XCTFail("expected unreadable, got \(error)")
            }
        }
    }

    // MARK: - Round trip

    /// What this app writes, it can read — and the document it writes carries the
    /// same keys the vector does.
    func testWhatWeWriteIsWhatTheVectorLooksLike() throws {
        let original = try SyncPayloadCodec.decode(try document(), currentSchemaVersion: 16)
        let encoded = try SyncPayloadCodec.encode(original)
        let again = try SyncPayloadCodec.decode(encoded, currentSchemaVersion: 16)

        XCTAssertEqual(again, original)

        // The keys, against Node's own document rather than against ourselves.
        let ours = try XCTUnwrap(
            try JSONSerialization.jsonObject(with: encoded) as? [String: Any]
        )
        let theirs = try XCTUnwrap(
            try JSONSerialization.jsonObject(with: try document()) as? [String: Any]
        )
        XCTAssertEqual(Set(ours.keys), Set(theirs.keys))
    }

    func testEncodingIsStable() throws {
        let payload = try SyncPayloadCodec.decode(try document(), currentSchemaVersion: 16)

        XCTAssertEqual(
            try SyncPayloadCodec.encode(payload),
            try SyncPayloadCodec.encode(payload),
            "two encodings of one payload must be the same bytes"
        )
    }
}
